---
- name: Install bzip2 package with apt
  apt:
    name: bzip2
    state: present
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Install bzip2 package with dnf
  dnf:
    name: bzip2
    state: present
    update_cache: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version > '7'

- name: Install bzip2 package with yum
  yum:
    name: bzip2
    state: present
    update_cache: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version < '8'

- name: Download restic archive
  get_url:
    url: "{{ restic_dist_url }}"
    dest: "{{ restic_tmp_directory }}/restic_{{ restic_version }}_linux_{{ go_arch }}.bz2"
    force: true
    checksum: "sha256:{{ __restic_checksum }}"

- name: Unarchive "{{ restic_tmp_directory }}/restic_{{ restic_version }}_linux_{{ go_arch }}.bz2"
  command: bzip2 -d "{{ restic_tmp_directory }}/restic_{{ restic_version }}_linux_{{ go_arch }}.bz2"
  changed_when: true

- name: Ensure "{{ restic_bin_birectory }}" exists
  file:
    path: "{{ restic_bin_birectory }}"
    state: directory
    mode: 0755

- name: Copy "{{ restic_tmp_directory }}/restic_{{ restic_version }}_linux_{{ go_arch }}" to "{{ restic_bin_birectory }}/restic" and set permissions
  copy:
    src: "{{ restic_tmp_directory }}/restic_{{ restic_version }}_linux_{{ go_arch }}"
    dest: "{{ restic_bin_birectory }}/restic"
    remote_src: true
    owner: root
    group: root
    mode: 0111

- name: Remove "{{ restic_tmp_directory }}/restic_{{ restic_version }}_linux_{{ go_arch }}"
  file:
    path: "{{ restic_tmp_directory }}/restic_{{ restic_version }}_linux_{{ go_arch }}"
    state: absent
