---
- include_tasks: variables.yml

- include_tasks: facts.yml

- include_tasks: preflight.yml
  when: restic_installed_version.stdout < restic_version

- include_tasks: install.yml
  when: restic_installed_version.stdout < restic_version
