---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if restic responds correctly
      command: restic version
      changed_when: true
      register: restic_local_version

    - name: Show restic output version
      debug: var=restic_local_version.stdout
